### ISSUE TITLE
提一个bug？

### ISSUE THREAD

**Issue by wby238** [LZ0211/Wedge#10]
在这个网站上`http://www.23us.com/`抓取时，由于网站偶尔会出问题导致无法连接，但在log文件中一样会有相关记录，然而实际保存文件却不是连续的（eg:实际存在的文件为00001.json，00002.json，00003.json，00004.json，00005.json，00015.json，中间会缺少06-14的json文件）。

**Comment by LZ0211** [comment]
不是bug，程序遇到连接失败会自动重连，设置app.retry.chapter就是章节下载的重连次数，可以设为无限大，但是会阻塞后面的任务。所以默认为3次，失败后自动跳过进行下一个任务。
缺失的章节在下次更新的时候会重新尝试下载的。

**Comment by wby238** [comment]
原来如此，OK
