### ISSUE TITLE
EBK 转TXT

### ISSUE THREAD

**Issue by MrXCQ** [LZ0211/Wedge#13]
有偿求助EBK格式文件转TXT格式算法。

**Comment by LZ0211** [comment]
Ebk3格式主要有4部分：{Header}，{DYNData}，{Block}，{List}

【文件头部分】
{
4字节：“ebk3”
UInt32：HeaderKey
UInt32：HeaderLen
UInt32：HeaderSecret
{文件信息列表}
}

【文件信息列表】
长度：HeaderLen – 16，这部分数据是加密的。
{
{UInt32类型，信息数目}，
{ UInt32类型，UInt32长度，数据}，
{ UInt32类型，UInt32长度，数据}，
{ UInt32类型，UInt32长度，数据}
……
}
长度=sizeof{类型(4)，长度(4)，数据}
加密和解密用的算法很简单，用JS写就是这样的，注意因为JS中没有64位整型，所以这儿用了Long.js
```javascript
//32位整数转byte
function Byte(number){
    var buf = Buffer.alloc(4);
    buf.writeInt32LE(number);
    return buf.readUInt8();
}

class EBK3Crypt{
    //初始化密码
    constructor(key){
        this.holdrand = Long.fromInt(key);
    }
    //设置密码
    setKey(key){
        this.holdrand = Long.fromInt(key);
    }
    //每次加密运算后生成下一次的种子
    pbk_data_n(){
        this.holdrand = this.holdrand.multiply(214013).add(2531011);
        return this.holdrand.shiftRight(16).and(32767).toInt()
    }

    encodeByte(b){
        var b2 = Byte(b & 224);
        var b3 = Byte(b & 28);
        var b4 = Byte(b & 3);
        var b5 = Byte(this.pbk_data_n());
        b = Byte(b4 << 6 | b3 << 1 | b2 >> 5);
        b = Byte(~b);
        return Byte(b ^ b5);
    }

    decodeByte(b){
        var b2 = Byte(this.pbk_data_n());
        b ^= b2;
        b = Byte(~b);
        var b3 = Byte(b & 192);
        var b4 = Byte(b & 56);
        var b5 = Byte(b & 7);
        return Byte(b5 << 5 | b4 >> 1 | b3 >> 6);
    }

    encodeUInt32(value){
        var buf = Buffer.alloc(4);
        buf.writeUInt32LE(value);
        for (var i = 0; i < 4; i++)
        {
            buf[i] = this.encodeByte(buf[i]);
        }
        return buf.readUInt32LE();
    }

    decodeUInt32(value){
        var buf = Buffer.alloc(4);
        buf.writeUInt32LE(value);
        for (var i = 0; i < 4; i++)
        {
            buf[i] = this.decodeByte(buf[i]);
        }
        return buf.readUInt32LE();
    }

    encodeUInt16(value){
        var buf = Buffer.alloc(2);
        buf.writeUInt16LE(value);
        for (var i = 0; i < 2; i++)
        {
            buf[i] = this.encodeByte(buf[i]);
        }
        return buf.readUInt16LE();
    }

    decodeUInt16(value){
        var buf = Buffer.alloc(2);
        buf.writeUInt16LE(value);
        for (var i = 0; i < 2; i++)
        {
            buf[i] = this.decodeByte(buf[i]);
        }
        return buf.readUInt16LE();
    }

    encodeData(data, offset, len){
        offset = offset || 0;
        len = len || data.length;
        for (var i = offset; i < offset + len; i++)
        {
            data[i] = this.encodeByte(data[i]);
        }
        return data;
    }

    decodeData(data, offset, len){
        offset = offset || 0;
        len = len || data.length;
        for (var i = offset; i < offset + len; i++)
        {
            data[i] = this.decodeByte(data[i]);
        }
        return data;
    }
}
```

【DYNData结构】
这个结构的用途是记录章节列表的偏移与长度。只有4个量。
{
UInt32 结构长度;// 一般就是16B
UInt32 图书编号;// 掌阅用这个值判断哪本书
UInt32 章节列表偏移;
UInt32 章节列表长度;
}

【章节列表】
{
UInt32 章节数目;
UInt32  24Byte;//列表项中前7条的长度。
{章节列表项}
{章节列表项}
……
}
【章节列表项】
{
UInt32标题长度;
UInt32 章节索引; // 章节的索引号
UInt16 章节等级;
UInt16 数据类型;
UInt32 块偏移;// 章节数据块的偏移位置
UInt32 数据偏移; // 章节内容在解码后数据中的偏移位置
UInt32 数据长度;
Byte 章节标题[标题长度];   // 章节名称
}

加密数据用头结构中的解码密钥解密。
块偏移：章节数据块在ebk3文件中的位置。（加密）
章节标题：一般没什么用。（加密）
章节列表项一般按添加的顺序排列，可以用章节索引来排序。
数据类型：获取数据块时使用，以后再说。
数据偏移：一个章节数据块内可能存放不止一个章节
数据长度：章节内容的长度（单位：字节）。

【章节数据块】
{ 
{块信息} 
{块数据}
 }
【块信息】
{
	UInt32 头密码；
	UInt32 块信息长度；
	UInt32 解码密钥；
	{块信息列表}
}
【块信息列表】
与头结构中的基本一样。MinVersion1、MinTip2、CompressType3、CompressBlockSize4、DataType、locale6、Encoding7、ChapterIndex8、ChapterLevel9、ChapterTitle10、FileListOffset11、ChapterContentDecompressLen12、BlockSize13。
块信息中一般只用密钥和块信息长度，一个用来解密，一个用来跳过块信息。

【块数据】
{
UInt32 块数目；（加密）
UInt32 块1长度、块2长度、块3长度。。。（加密）
Byte 块1数据、块2数据、块3数据。。。（加密）
}
解密密码使用块信息中的。
章节信息项中，当数据类块型为0时，每个长度的解密需要重设密码。
块数据只加密了前16字节，因为这是压缩数据，改变几个字节就无法解压了。每块数据解压之后为64KB（65336）。将各块解密解压然后拼接起来就是章节块记录的内容（可能不止一个章节）。

**Comment by MrXCQ** [comment]
好的，非常感谢作者大佬！！EBK3.0、EBK2.0、EBK三种格式的算法都一样吗？

**Comment by LZ0211** [comment]
EBK3是这样的，因为iReader有win10客户端，可以看到C#源码，EBK2的格式不清楚。
