### ISSUE TITLE
书客的规则好像失效了

### ISSUE THREAD

**Issue by wby238** [LZ0211/Wedge#5]
刚刚试了下[这本](http://www.hbooker.com/book/book_detail/100000454)，发现爬下来的章节内容都是undefined。

```json
{
  "title": "本书中比企谷八幡的资料",
  "id": "00000",
  "source": "http://www.hbooker.com/chapter/book_chapter_detail/100068865",
  "date": 1492498776504,
  "content": "undefined"
}
```

**Comment by LZ0211** [comment]
书客的内容是加密的，和网易云音乐差不多。没有仔细去分析加密函数，token已经能够拿到，解密函数还没写。
有时间我会定期更新各种网站规则的。

**Comment by LZ0211** [comment]
已更新规则，书客下载时线程请设为1，多线程会触发反爬虫机制。
